remote_theme: "mmistakes/minimal-mistakes@4.28.1"
plugins:
  - jekyll-include-cache
include: ["_pages"]
minimal_mistakes_skin: "dark"
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"